# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HGTableViewTransform' do

  # 很实用的基类
  pod 'HGBaseClass'
  
  # 具体功能看官网吧
  pod 'SlackTextViewController'

end
